#!/bin/bash

#Fail this script should any operation fail
set -e
set -o pipefail

# Utility functions
##########

function enforce_root {
    if [ "$(whoami)" != "root" ];
    then
        echo "Please re-run this script as root (eg: 'sudo bash <script>').";
        echo "#####"
        exit;
    fi
}

# Takes two arguments, $ALIAS_NAME and $COMMAND_TEXT
function add_alias_if_missing {
    ALIAS_NAME=$1;
    COMMAND_TEXT=$2;

    if [ -z "$ALIAS_NAME" ] || [ -z "$COMMAND_TEXT" ];
    then
        echo "add_alias_if_missing was provided invalid arguments: $1 and $2."
        echo "#####"
        exit;
    fi

    if ! grep -q "alias $ALIAS_NAME" ~/.bashrc;
    then
        echo "# This alias ('$ALIAS_NAME') was added by cjjeakle's ubuntu-tools setup script" >> ~/.bashrc
        echo "alias $ALIAS_NAME=\"$COMMAND_TEXT\"" >> ~/.bashrc
    fi
}

# Checks, user input, and input validation
##########

enforce_root;

echo "This script will install commonly used tools."
echo "#####"

# The config script
##########

echo "Installing apt packages."
echo "#####"
# Add Sublime Text (stable) to apt
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list
# Add nodejs (v6 LTS) to apt
curl -sL https://deb.nodesource.com/setup_6.x | bash -
# Update apt
apt update
# Common dev tools
apt -y install clang curl g++ git gnupg grep nano nodejs vim postgresql python3-pip screen sed sublime-text

echo "Installing RVM, Ruby, and Bundler."
echo "#####"
# Install RVM, ruby, and rubygems (as a part of the ruby install)
su - $SUDO_USER -c "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\\curl -sSL https://get.rvm.io | bash -s stable --ruby"
# Other GitHub pages dependencies
su - $SUDO_USER -c "source /home/$SUDO_USER/.rvm/scripts/rvm"
su - $SUDO_USER -c "gem install bundler"

echo "Making a projects directory."
echo "#####"
su - $SUDO_USER -c "mkdir -p ~/Projects"

echo "Adding convenience shortcuts."
echo "#####"
add_alias_if_missing "upgrade" "sudo apt -y update && sudo apt -y upgrade && sudo apt -y autoremove"
add_alias_if_missing "proj" "cd ~/Projects/"
add_alias_if_missing "serv" "python3 -m http.server 4000"
add_alias_if_missing "python" "python3"
add_alias_if_missing "pip" "pip3"

echo "-----"
echo "#####"
echo "Done!"
echo "To use RVM, run 'source /home/$SUDO_USER/.rvm/scripts/rvm'."
echo "To use the newly added shortcuts, run 'source ~/.bashrc'."
echo "#####"
echo "-----"
